# -*- coding: utf-8 -*-
"""Authoring source for the beat sheet. Emits content/qingmao/acts/<act>/beats.json.

Kept as a generator so the 68 beats stay structurally identical; the prose and the
flag wiring below are the authored content.
"""
import json, pathlib, collections

# Legacy step anchors from the previous build's save format (v4, 76 stages):
# steps 0-8 -> ch 1-50, 8-24 -> 51-100, 24-44 -> 101-150, 44-76 -> 151-200.
ANCHORS = [(1, 50, 0, 8), (51, 100, 8, 24), (101, 150, 24, 44), (151, 200, 44, 76)]

def legacy_step(last_chapter):
    for c0, c1, s0, s1 in ANCHORS:
        if c0 <= last_chapter <= c1:
            t = (last_chapter - c0 + 1) / (c1 - c0 + 1)
            return round(s0 + t * (s1 - s0))
    raise ValueError(last_chapter)

B = collections.namedtuple('B', 'id act ch cov title template area must sets requires reads evidence recollection foresight art day weather cast note', defaults=(None,)*8 + ((), (), (), (), None, None, None, 1, 'clear', (), None))

def b(id, act, ch, cov, title, template, area, must=None, sets=(), requires=(), reads=(),
      evidence=(), recollection=None, foresight=None, art=None, day=1, weather='clear', cast=(), note=None):
    return B(id, act, ch, cov, title, template, area, must, sets, requires, reads, evidence,
             recollection, foresight, art, day, weather, cast, note)

BEATS = [
# ---------------------------------------------------------------- ACT I
b('prologue.last-stand', 'act1', (1, 2), 'played', 'The last stand of the first life', 'boss-gauntlet',
  'prologue.last-stand', must=1, sets=('prologue.done', 'gu.cicada'),
  art='prologue-last-stand', day=0, weather='storm',
  cast=('fang-yuan', 'narrator'),
  note='Full power, hopeless odds. Also the combat tutorial, so the drop to Rank one in the next beat has something to be a drop from.'),
b('act1.waking.bamboo-room', 'act1', (3, 3), 'played', 'Rain on the upper floor', 'waking',
  'mountain.hostel-room', sets=('rank.0', 'calendar.start'), requires=('prologue.last-stand',),
  recollection='Five hundred years of it, and the first thing he checks is the window latch.',
  art='bamboo-dawn', day=1, weather='rain', cast=('fang-yuan',),
  note='First inner-voice line, first Recollection, movement tutorial. Weak on purpose.'),
b('act1.awakening.ceremony', 'act1', (4, 6), 'staged', 'Forty-four percent', 'ceremony',
  'mountain.awakening-river', must=2, sets=('rank.1.initial', 'aptitude.c', 'know.fang-zheng-a-grade'),
  requires=('act1.waking.bamboo-room',), recollection='He already knows the number the elder is about to read out.',
  foresight='Stand on the far bank before the orchids are named and the ceremony reads differently.',
  art='awakening', day=11, weather='mist', cast=('fang-yuan', 'fang-zheng', 'elder-gu-room', 'narrator'),
  note='Crowd reactions staged in the round. His inner reading of the verdict runs over the elder\'s lines.'),
b('act1.academy.first-gu', 'act1', (7, 8), 'played', 'The crescent in your palm', 'gu-selection',
  'mountain.gu-room', sets=('gu.moonlight', 'econ.stones-open', 'know.tavern'),
  requires=('act1.awakening.ceremony',), art=None, day=14, weather='clear',
  cast=('fang-yuan', 'elder-gu-room', 'tavern-keeper'),
  note='First upkeep explained here: Moonlight Gu eats moon orchid petals. The stone ledger opens.'),
b('act1.household.brothers', 'act1', (9, 11), 'staged', 'A house that is not his', 'household-scene',
  'mountain.uncle-house', sets=('know.assets-dispute', 'know.uncle'),
  requires=('act1.academy.first-gu',), art=None, day=18, weather='rain',
  cast=('fang-yuan', 'fang-qiu', 'fang-qiu-wife', 'fang-zheng'),
  note='The brothers begin to diverge and the asset dispute is seeded. Restores an arc the old build skipped.'),
b('act1.liquor-worm.search', 'act1', (12, 13), 'played', 'A jar bought with tomorrow', 'search-lure',
  'mountain.bamboo-grove', sets=('item.wine', 'know.liquor-worm'), requires=('act1.academy.first-gu',),
  recollection='A wine-loving Gu lives on this mountain. He does not remember which crevice.',
  foresight='Walk the grove before calling the memory up and the lure can be set on the first night.',
  art='bamboo-dawn', day=22, weather='mist', cast=('fang-yuan', 'tavern-keeper'),
  note='Several nights of searching, not one visit. The Recollection points at an opportunity, never a waypoint.'),
b('act1.liquor-worm.cave', 'act1', (14, 19), 'played', 'What the mountain remembers', 'cave-inheritance',
  'mountain.flower-wine-cave', must=3, sets=('gu.liquor-worm', 'know.image-wall', 'secret.liquor-worm-origin'),
  requires=('act1.liquor-worm.search',), evidence=('cave.entry-traces',),
  foresight='The image wall contradicts the clan before anyone in the game says so.',
  art='lotus-chamber', day=31, weather='clear', cast=('fang-yuan', 'flower-wine-monk', 'narrator'),
  note='Genuinely dark; the player carries the light. The Cicada\'s pressure is a set piece with a fixed outcome.'),
b('act1.cultivation.first-weeks', 'act1', (20, 21), 'ledger', 'Weeks of small sums', 'ledger-only',
  'mountain.hostel-room', sets=('know.liquor-worm-limits',), requires=('act1.liquor-worm.cave',),
  day=36, weather='clear', cast=('fang-yuan',),
  note='The Liquor worm stops refining Rank two essence. Recorded, not played.'),
b('act1.academy.moonblade', 'act1', (22, 24), 'played', 'Control, before force', 'training-drill',
  'mountain.training-yard', sets=('skill.moonblade',), requires=('act1.academy.first-gu',),
  day=40, weather='clear', cast=('fang-yuan', 'elder-gu-room'),
  note='Three nonliving practice targets. Every strike shows its essence cost.'),
b('act1.extortion.toll', 'act1', (25, 29), 'played', 'An after-class arrangement', 'extortion-loop',
  'mountain.academy-gate', must=4, sets=('econ.toll-income', 'secret.extortion'),
  requires=('act1.academy.moonblade',), evidence=('toll.witnesses', 'toll.ledger-gap'),
  day=44, weather='clear', cast=('fang-yuan', 'mo-yan'),
  note='Recurs over several in-game days. The player chooses the rate and how visible it is.'),
b('act1.extortion.elder-counters', 'act1', (30, 33), 'staged', 'Someone has started counting', 'escalation',
  'mountain.academy-classroom', sets=('flag.elder-watching', 'know.mo-family'),
  requires=('act1.extortion.toll',), reads=('toll.witnesses',), evidence=('toll.elder-report',),
  day=52, weather='rain', cast=('fang-yuan', 'academy-elder-mo', 'mo-bei', 'mo-yan'),
  note='The academy elder is the first adult who is a real obstacle. The Mo family escalates behind him.'),
b('act1.extortion.servant', 'act1', (34, 37), 'played', 'A man sent to settle it', 'confrontation-choice',
  'mountain.bamboo-path', sets=('secret.mo-servant',), requires=('act1.extortion.elder-counters',),
  evidence=('servant.body', 'servant.livery', 'servant.witness'),
  day=60, weather='mist', cast=('fang-yuan', 'mo-servant'),
  note='The choice is on screen; the blow is cut away from. Aftermath runs through guards, classroom whispers and changed NPC remarks.'),
b('act1.extortion.negotiation', 'act1', (38, 38), 'played', 'Composure as the weapon', 'negotiation',
  'mountain.academy-classroom', must=4, sets=('econ.mo-settlement', 'flag.extortion-closed'),
  requires=('act1.extortion.servant',), reads=('servant.witness', 'toll.elder-report'),
  day=68, weather='clear', cast=('fang-yuan', 'mo-bei', 'academy-elder-mo'),
  note='No combat. What the player left behind sets how much he has to concede.'),
b('act1.caravan.gambling', 'act1', (39, 42), 'played', 'Inside the purple-gold shell', 'gambling',
  'mountain.caravan-market', sets=('econ.gambling-open', 'gu.mudskin-toad'),
  requires=('act1.extortion.negotiation',), day=72, weather='clear',
  cast=('fang-yuan', 'caravan-merchant'),
  note='Stone gambling as a real mini-game with real losses. Its point is the next beat.'),
b('act1.caravan.fossil', 'act1', (43, 43), 'played', 'A story others will believe', 'trade',
  'mountain.caravan-market', sets=('item.fossil', 'cover.liquor-worm'),
  requires=('act1.caravan.gambling',), day=78, weather='clear',
  cast=('fang-yuan', 'caravan-merchant'),
  note='The fossil is the cover story. Its real value is as evidence at the inquiry.'),
b('act1.jia-jin-sheng.night', 'act1', (44, 49), 'played', 'Someone on the path behind you', 'stealth-confrontation',
  'mountain.bamboo-path', must=5, sets=('secret.jjs',), requires=('act1.caravan.fossil',),
  evidence=('jjs.trail', 'jjs.witness', 'jjs.gu-residue', 'jjs.missing-report'),
  art='reader-cicada', day=84, weather='mist', cast=('fang-yuan', 'jia-jin-sheng'),
  note='Notice the tail, choose where to lead him, then the cleanup. Every piece left behind is recorded for chapter 51.'),
b('act1.breakthrough.middle-stage', 'act1', (50, 50), 'played', 'Rank one, middle stage', 'breakthrough-ritual',
  'mountain.hostel-room', sets=('rank.1.middle',), requires=('act1.jia-jin-sheng.night',),
  day=92, weather='rain', cast=('fang-yuan',),
  note='A staged ritual, not a quest-complete pop-up. Act I closes on an autosave and a title card.'),
# ---------------------------------------------------------------- ACT II
b('act2.inquiry.jia-fu', 'act2', (51, 59), 'played', 'The question beneath the question', 'inquiry',
  'mountain.clan-hall', must=5, sets=('flag.inquiry-passed', 'know.tie-xue-leng'),
  requires=('act1.breakthrough.middle-stage',),
  reads=('jjs.trail', 'jjs.witness', 'jjs.gu-residue', 'jjs.missing-report', 'cover.liquor-worm'),
  art='reader-hall', day=104, weather='clear', cast=('fang-yuan', 'jia-fu', 'elder-bo'),
  note='Exposure payoff one. A clean trail is a calm conversation; a messy one costs lies, stones and favours. He is never caught.'),
b('act2.inheritance.image-wall', 'act2', (60, 61), 'played', 'Beyond the recorded history', 'wall-break',
  'mountain.flower-wine-cave', sets=('flag.wall-open',), requires=('act2.inquiry.jia-fu',),
  day=118, weather='clear', cast=('fang-yuan', 'narrator'),
  note='The Photo-audio Gu is exhausted; the wall becomes ordinary stone. Knowing where to look is what is left.'),
b('act2.academy.little-light', 'act2', (62, 63), 'staged', 'A star beside the crescent', 'gu-selection',
  'mountain.gu-room', sets=('gu.little-light',), requires=('act2.inheritance.image-wall',),
  day=122, weather='clear', cast=('fang-yuan', 'elder-gu-room')),
b('act2.inheritance.earth-treasury', 'act2', (64, 64), 'played', 'The seed of strength', 'cave-inheritance',
  'mountain.earth-treasury', must=6, sets=('gu.white-boar',), requires=('act2.inheritance.image-wall',),
  art='lotus-chamber', day=124, weather='clear', cast=('fang-yuan', 'narrator'),
  note='Each advantage the inheritance hands over answers the obstacle after it.'),
b('act2.hunter.map', 'act2', (65, 69), 'played', 'Knowledge carried in bamboo', 'stealth-confrontation',
  'mountain.hunter-rest', sets=('item.beast-map', 'secret.hunter-map'),
  requires=('act2.inheritance.earth-treasury',), evidence=('map.owner-missing', 'map.copy-mismatch'),
  art='reader-map', day=130, weather='rain', cast=('fang-yuan', 'wang-da'),
  note='Restores the actual acquisition the old docs replaced with an abandoned camp. Coercion staged, violence cut away from.'),
b('act2.boar.strength', 'act2', (70, 73), 'played', 'Strength that stays', 'hunt-loop',
  'mountain.boar-trail', sets=('stat.strength', 'econ.boar-blood'), requires=('act2.hunter.map',),
  day=138, weather='clear', cast=('fang-yuan',),
  note='Hunting route from the map. Feeding White Boar Gu is also the cheapest diet in the game, which is the lesson.'),
b('act2.wang-da.inference', 'act2', (74, 77), 'played', 'The red circles', 'inference',
  'mountain.wang-hideout', sets=('know.wang-da',), requires=('act2.boar.strength',),
  reads=('map.copy-mismatch',), day=146, weather='mist', cast=('fang-yuan',),
  note='A portrait, a cooking fire, concealed markings. He avoids the fight by knowing the mountain better.'),
b('act2.mission.roster', 'act2', (78, 78), 'staged', 'Names on a roster', 'mission-brief',
  'mountain.affairs-hall', sets=('know.jiao-san',), requires=('act2.wang-da.inference',),
  day=152, weather='clear', cast=('fang-yuan', 'jiao-san', 'elder-bo'),
  note='Seeds the winter group so chapters 93-96 cost something.'),
b('act2.inheritance.boulder', 'act2', (79, 79), 'played', 'What strength is for', 'boulder-push',
  'mountain.inheritance-passage', must=6, sets=('gu.jade-skin', 'flag.boar-ceiling'),
  requires=('act2.boar.strength',), day=159, weather='clear', cast=('fang-yuan',),
  note='White Boar Gu stops granting strength here. The boulder is the wall that proves it was enough.'),
b('act2.inheritance.stone-forest', 'act2', (80, 81), 'played', 'Eyes above the path', 'stone-forest',
  'mountain.stone-forest', must=6, sets=('flag.monkeys-known',), requires=('act2.inheritance.boulder',),
  art='stone-forest', day=164, weather='clear', cast=('fang-yuan',),
  note='Ceiling, darkness, carried light. The jade-eye monkeys conceal themselves and their stone bodies come apart.'),
b('act2.duel.preparation', 'act2', (82, 84), 'staged', 'Before the examination', 'escalation',
  'mountain.academy', sets=('know.fang-zheng-defences',), requires=('act2.inheritance.stone-forest',),
  day=172, weather='clear', cast=('fang-yuan', 'fang-zheng', 'elder-gu-room'),
  note='The player is shown what to read during the duel. Readers get the dramatic irony for free.'),
b('act2.duel.fang-zheng', 'act2', (85, 87), 'played', 'The year-end duel', 'duel',
  'mountain.arena', must=7, sets=('flag.duel-won',), requires=('act2.duel.preparation',),
  reads=('know.fang-zheng-defences',), day=180, weather='clear',
  cast=('fang-yuan', 'fang-zheng', 'elder-gu-room'),
  note='Multi-phase. Each phase is a defence to read, not a vitality bar to out-damage.'),
b('act2.winter.mission-brief', 'act2', (88, 90), 'played', 'Permafrost and decayed soil', 'mission-brief',
  'mountain.winter-grounds', must=8, sets=('item.decayed-soil', 'econ.mission-pay'),
  requires=('act2.duel.fang-zheng',), day=278, weather='snow',
  cast=('fang-yuan', 'jiao-san'),
  note='Clan obligations start competing with cultivation time. The calendar does the arguing.'),
b('act2.secret.rank-two', 'act2', (91, 92), 'played', 'Red steel, quietly', 'secret-cultivation',
  'mountain.jiang-he-refuge', must=8, sets=('rank.2.initial', 'secret.rank-two'),
  requires=('act2.winter.mission-brief',), evidence=('rank2.essence-colour', 'rank2.absence'),
  art='reader-cultivation', day=288, weather='snow', cast=('fang-yuan', 'jiang-he'),
  note='A breakthrough ritual performed in secret. The secrecy is itself an exposure risk from here on.'),
b('act2.winter.boar-king', 'act2', (93, 96), 'played', 'Inside the boar king', 'beast-crossing',
  'mountain.beast-crossing', must=8, sets=('item.snowy-tusk', 'know.group-losses'),
  requires=('act2.secret.rank-two',), art='frozen-qing-mao', day=298, weather='snow',
  cast=('fang-yuan', 'jiao-san', 'narrator'),
  note='The group losses are played, not summarised. Survival inside the carcass is the sequence, and it is cut away from at the right moment.'),
b('act2.affairs.application', 'act2', (97, 98), 'staged', 'An application, and an inquiry into a loss', 'petition',
  'mountain.affairs-hall', must=9, sets=('flag.assets-applied',), requires=('act2.winter.boar-king',),
  reads=('know.group-losses',), day=306, weather='snow', cast=('fang-yuan', 'elder-bo'),
  note='The family-asset mission opens here and is not settled until chapter 115.'),
b('act2.refinement.white-jade', 'act2', (99, 100), 'played', 'White Jade', 'refinement',
  'mountain.forge', sets=('gu.white-jade',), requires=('act2.affairs.application',),
  reads=('item.snowy-tusk',), day=312, weather='snow', cast=('fang-yuan',),
  note='Canonical refinement: it cannot fail outright. Without the tusk it costs more days and more stones.'),
# ---------------------------------------------------------------- ACT III
b('act3.assets.petition', 'act3', (101, 104), 'played', 'What the ledger says is his', 'petition',
  'mountain.affairs-hall', must=9, sets=('know.asset-records', 'know.man-shi'),
  requires=('act2.refinement.white-jade',), day=320, weather='clear',
  cast=('fang-yuan', 'fang-qiu', 'elder-bo', 'man-shi'),
  note='The squeeze starts on paper. Spawn point sits beside the hall, not a hundred and ninety paces away.'),
b('act3.assets.witnesses', 'act3', (105, 108), 'played', 'People who remember the arrangement', 'witness-gathering',
  'mountain.village', sets=('econ.witness-costs',), requires=('act3.assets.petition',),
  evidence=('assets.pressure-witness',), day=328, weather='rain',
  cast=('fang-yuan', 'fang-qiu-wife', 'tavern-keeper'),
  note='Pressure, payment or patience. All three reach the same settlement at different prices.'),
b('act3.assets.council', 'act3', (109, 112), 'staged', 'A matter for the council', 'council',
  'mountain.clan-hall', sets=('flag.council-heard',), requires=('act3.assets.witnesses',),
  reads=('econ.witness-costs',), art='reader-hall-steps', day=338, weather='clear',
  cast=('fang-yuan', 'fang-qiu', 'elder-bo')),
b('act3.assets.settlement', 'act3', (113, 115), 'played', 'The property changes hands', 'settlement',
  'mountain.affairs-hall', must=9, sets=('econ.property', 'flag.assets-won'),
  requires=('act3.assets.council',), day=348, weather='clear',
  cast=('fang-yuan', 'fang-qiu', 'fang-zheng'),
  note='Unlocks the tavern and property loop. Fang Zheng is in the room and says the wrong thing.'),
b('act3.bai.interlude', 'act3', (116, 116), 'staged', 'A clan that keeps its own accounts', 'interlude',
  'bai.hall', sets=('know.bai-ning-bing',), requires=('act3.assets.settlement',),
  art='reader-white-robes', day=352, weather='clear', cast=('bai-ning-bing',),
  note='Viewpoint interlude. Bai\'s one-arm model ships here and stays until chapter 199.'),
b('act3.leaves.nine-leaf', 'act3', (117, 118), 'played', 'Nine leaves and a buyer', 'farm-loop',
  'mountain.leaf-terraces', sets=('gu.nine-leaf', 'econ.leaf-income'),
  requires=('act3.assets.settlement',), day=356, weather='rain',
  cast=('fang-yuan', 'jiang-ya'),
  note='The most reliable income in the game, and the only healing. Both facts matter at chapter 200.'),
b('act3.moonglow.failure', 'act3', (119, 121), 'played', 'A refinement that does not take', 'refinement',
  'mountain.forge', sets=('flag.moonglow-failed',), requires=('act3.leaves.nine-leaf',),
  day=4, weather='clear', cast=('fang-yuan',),
  note='The scripted first failure stays. It costs days and stones, never the Gu.'),
b('act3.moonglow.success', 'act3', (122, 124), 'played', 'Moonglow', 'refinement',
  'mountain.forge', sets=('gu.moonglow',), requires=('act3.moonglow.failure',),
  day=14, weather='clear', cast=('fang-yuan',)),
b('act3.tavern.property', 'act3', (125, 127), 'played', 'Staff, stock and troublemakers', 'property-loop',
  'mountain.tavern', sets=('econ.tavern-income',), requires=('act3.assets.settlement',),
  reads=('know.man-shi',), day=20, weather='clear', cast=('fang-yuan', 'tavern-keeper', 'man-shi'),
  note='Two floors, a wage bill and Man Shi. Feeds the economy and the codex, never filler.'),
b('act3.four-flavours.refinement', 'act3', (128, 131), 'played', 'Four Flavours', 'refinement',
  'mountain.forge', sets=('gu.four-flavours', 'gu.black-boar'), requires=('act3.tavern.property',),
  day=28, weather='clear', cast=('fang-yuan',),
  note='Needs a second Liquor worm. The upkeep after this is meant to hurt.'),
b('act3.stealth-scales', 'act3', (132, 134), 'played', 'Scales and an ear in the soil', 'trade',
  'mountain.medicine-hall', sets=('gu.stealth-scales', 'gu.earth-ear'),
  requires=('act3.four-flavours.refinement',), day=38, weather='rain',
  cast=('fang-yuan', 'jiang-ya')),
b('act3.wolf-tide.warnings', 'act3', (135, 138), 'staged', 'The season nobody argues with', 'escalation',
  'mountain.village', sets=('know.wolf-tide', 'gu.water-shield'),
  requires=('act3.stealth-scales',), day=48, weather='mist',
  cast=('fang-yuan', 'qing-shu', 'elder-bo'),
  note='Weather turns with the calendar. Qing Shu is established here so chapter 145 costs something.'),
b('act3.wolf-tide.forest', 'act3', (139, 142), 'played', 'Lightning in the undergrowth', 'wolf-tide',
  'mountain.wolf-forest', must=10, sets=('flag.tide-entered',), requires=('act3.wolf-tide.warnings',),
  reads=('gu.stealth-scales', 'gu.earth-ear'), art='reader-red-storm', day=56, weather='storm',
  cast=('fang-yuan', 'narrator'),
  note='Sub-types and pack behaviour. Concealment is the intended answer; fighting is the expensive one.'),
b('act3.qing-shu.last-stand', 'act3', (143, 145), 'played', 'A position that does not hold', 'observer',
  'mountain.wolf-forest', must=10, sets=('know.qing-shu-death',), requires=('act3.wolf-tide.forest',),
  day=62, weather='storm', cast=('fang-yuan', 'qing-shu', 'narrator'),
  note='The observer framing is the scene. The player can leave at any moment and the game never asks them to stay.'),
b('act3.aftermath.tally', 'act3', (146, 149), 'ledger', 'The tally after the tide', 'ledger-only',
  'mountain.village', sets=('econ.tide-aftermath',), requires=('act3.qing-shu.last-stand',),
  day=70, weather='mist', cast=('fang-yuan',)),
b('act3.yao-le.encounter', 'act3', (150, 150), 'played', 'Someone who recognises him', 'confrontation-choice',
  'mountain.wolf-forest', must=11, sets=('know.yao-le',), requires=('act3.aftermath.tally',),
  day=76, weather='rain', cast=('fang-yuan', 'yao-le'),
  note='Act III ends on the encounter, not on what follows. Give her enough lines to be a person first.'),
# ---------------------------------------------------------------- ACT IV
b('act4.yao-le.rank-three', 'act4', (151, 152), 'played', 'A cost that cannot be undone', 'breakthrough-ritual',
  'mountain.wolf-forest', must=11, sets=('rank.3.initial', 'secret.yao-le'),
  requires=('act3.yao-le.encounter',), evidence=('yaole.absence', 'yaole.last-seen', 'yaole.ritual-site'),
  day=80, weather='rain', cast=('fang-yuan', 'yao-le', 'narrator'),
  note='The choice is on screen; the act is off screen; the breakthrough is a full ritual. Three pieces of evidence enter the world.'),
b('act4.council.elder', 'act4', (153, 154), 'staged', 'An elder with a faction behind him', 'council',
  'mountain.clan-hall', sets=('flag.elder-rank', 'know.chi-lian'),
  requires=('act4.yao-le.rank-three',), art='reader-hall', day=84, weather='clear',
  cast=('fang-yuan', 'elder-bo', 'chi-lian'),
  note='Yao Ji begins appearing in the village between beats from here on.'),
b('act4.forge.elder-tools', 'act4', (155, 155), 'played', 'Tools for leaving', 'refinement',
  'mountain.forge', sets=('gu.sky-canopy', 'gu.thunderwings'), requires=('act4.council.elder',),
  day=88, weather='clear', cast=('fang-yuan',),
  note='Sky Canopy replaces White Jade. The upkeep jump is the point of the promotion.'),
b('act4.forge.blood-moon', 'act4', (156, 157), 'played', 'A moon not bound to orchids', 'refinement',
  'mountain.forge', sets=('gu.blood-moon',), requires=('act4.forge.elder-tools',),
  art='reader-cultivation', day=94, weather='clear', cast=('fang-yuan',),
  note='Chosen because its diet does not chain him to clan supplies after he leaves.'),
b('act4.medicine.order', 'act4', (158, 159), 'staged', 'An order from a younger man', 'council',
  'mountain.medicine-hall', sets=('flag.medicine-pressure',), requires=('act4.forge.blood-moon',),
  day=100, weather='rain', cast=('fang-yuan', 'chi-zhong')),
b('act4.village.search', 'act4', (160, 163), 'played', 'The same question, for weeks', 'witness-gathering',
  'mountain.village', sets=('flag.search-pressure',), requires=('act4.medicine.order',),
  reads=('yaole.absence', 'yaole.last-seen'), evidence=('search.inconsistency',),
  day=110, weather='mist', cast=('fang-yuan', 'yao-ji', 'man-shi'),
  note='Yao Ji asks everyone. Cleanup here is the last chance before Tie Ruo Nan arrives.'),
b('act4.centipede.equip', 'act4', (164, 166), 'played', 'Something for close range', 'trade',
  'mountain.forge', sets=('gu.centipede',), requires=('act4.village.search',),
  day=120, weather='clear', cast=('fang-yuan',)),
b('act4.supplies.tusita', 'act4', (167, 169), 'played', 'Packing for a road he has not named', 'trade',
  'mountain.medicine-hall', sets=('gu.tusita', 'flag.supplies-ready'),
  requires=('act4.centipede.equip',), day=128, weather='clear',
  cast=('fang-yuan', 'chi-zhong'),
  note='He is provisioning for departure thirty chapters before he leaves. Readers should notice.'),
b('act4.investigation.arrival', 'act4', (170, 173), 'played', 'An investigator who expects to be lied to', 'investigation',
  'mountain.clan-hall', must=12, sets=('know.tie-ruo-nan',), requires=('act4.supplies.tusita',),
  reads=('jjs.trail', 'jjs.witness', 'yaole.absence', 'search.inconsistency'),
  art='reader-touzi', day=136, weather='clear',
  cast=('fang-yuan', 'tie-ruo-nan', 'jia-fu', 'elder-bo'),
  note='Exposure payoff two. She opens on whatever the player actually left, all the way back to chapter 44.'),
b('act4.investigation.trail', 'act4', (174, 177), 'played', 'Working the trail', 'investigation',
  'mountain.village', must=12, sets=('flag.trail-worked',), requires=('act4.investigation.arrival',),
  reads=('servant.witness', 'map.owner-missing', 'rank2.absence', 'yaole.ritual-site'),
  day=144, weather='rain', cast=('fang-yuan', 'tie-ruo-nan', 'tie-xue-leng'),
  note='She visits the places. A clean trail is calm and cheap; a messy one costs lies, bribes and days.'),
b('act4.investigation.theory', 'act4', (178, 181), 'played', 'A theory that is wrong', 'investigation',
  'mountain.clan-hall', must=12, sets=('flag.investigation-closed',),
  requires=('act4.investigation.trail',), reads=('flag.trail-worked',),
  day=152, weather='clear', cast=('fang-yuan', 'tie-ruo-nan', 'tie-xue-leng', 'elder-bo'),
  note='As in canon he is never caught. It should read as a near miss the player earned, not as a gift.'),
b('act4.deep-inheritance.founder', 'act4', (182, 185), 'played', 'Under the clan', 'cave-inheritance',
  'mountain.deep-inheritance', must=13, sets=('gu.treasure-lotus', 'know.founder'),
  requires=('act4.investigation.theory',), art='lotus-chamber', day=160, weather='clear',
  cast=('fang-yuan', 'gu-yue-founder', 'narrator'),
  note='The room has to feel too large. Nothing here is a fight the player can win.'),
b('act4.blood-lake.stone-aperture', 'act4', (186, 189), 'played', 'What advancement costs', 'cave-inheritance',
  'mountain.blood-lake', must=13, sets=('rank.3.peak', 'flag.aperture-spent'),
  requires=('act4.deep-inheritance.founder',), day=168, weather='clear',
  cast=('fang-yuan', 'lord-sky-crane', 'narrator'),
  note='Stone Aperture Gu is expended. Rank three peak, and the chance of anything beyond it spent.'),
b('act4.founder.sky-crane', 'act4', (190, 193), 'played', 'Two powers over one mountain', 'cinematic',
  'mountain.blood-lake', must=13, sets=('know.fang-zheng-taken',),
  requires=('act4.blood-lake.stone-aperture',), art='uneasy-alliance', day=176, weather='storm',
  cast=('fang-yuan', 'gu-yue-founder', 'lord-sky-crane', 'fang-zheng', 'bai-ning-bing'),
  note='Staged so both read as out of the player\'s league. Fang Zheng is carried off, alive.'),
b('act4.blood-curtain.decision', 'act4', (194, 197), 'played', 'The curtain', 'cinematic',
  'mountain.blood-lake', must=14, sets=('flag.curtain-raised',), requires=('act4.founder.sky-crane',),
  art='reader-red-storm', day=179, weather='storm',
  cast=('fang-yuan', 'bai-ning-bing', 'narrator'),
  note='The decision is on screen. Mass death is staged through aftermath and reaction, never as a scoring mechanic.'),
b('act4.blood-curtain.cicada', 'act4', (198, 198), 'played', 'Spring, then autumn', 'cinematic',
  'mountain.glacier', must=14, sets=('flag.cicada-used',), requires=('act4.blood-curtain.decision',),
  art='frozen-qing-mao', day=181, weather='snow', cast=('fang-yuan', 'narrator'),
  note='The one rewind, fixed. A cinematic sequence with a fixed outcome, not a combat arena.'),
b('act4.bai.transformation', 'act4', (199, 199), 'played', 'Yin, and what it changes', 'cinematic',
  'mountain.glacier', must=15, sets=('gu.yang', 'flag.bai-restored', 'flag.no-healing-gu'),
  requires=('act4.blood-curtain.cicada',), art='uneasy-alliance', day=183, weather='snow',
  cast=('fang-yuan', 'bai-ning-bing'),
  note='Bai\'s model swaps to the restored variant here. The Yang Gu stays with Fang Yuan; that is the sequel\'s lever.'),
b('act4.escape.raft', 'act4', (200, 200), 'played', 'The Yellow Dragon River', 'escape',
  'mountain.yellow-dragon-river', must=15, sets=('rank.1.initial', 'flag.ending', 'legacy.available'),
  requires=('act4.bai.transformation',), art='yellow-dragon-river', day=184, weather='mist',
  cast=('fang-yuan', 'bai-ning-bing', 'narrator'),
  note='Rank one again, no healing Gu, the Southern Border ahead. Offers the Legacy export and the Unfinished business page.'),
]

# ---- validation ------------------------------------------------------------
def main():
    covered = {}
    ids = set()
    all_sets = set()
    for x in BEATS:
        assert x.id not in ids, f'duplicate beat id {x.id}'
        ids.add(x.id)
        all_sets |= set(x.sets)
        for c in range(x.ch[0], x.ch[1] + 1):
            assert c not in covered, f'chapter {c} covered twice: {covered.get(c)} and {x.id}'
            covered[c] = x.id
    missing = [c for c in range(1, 201) if c not in covered]
    assert not missing, f'chapters with no beat: {missing}'
    for x in BEATS:
        for r in x.requires:
            assert r in ids, f'{x.id} requires unknown beat {r}'
    evidence_ids = {e for x in BEATS for e in x.evidence}
    for x in BEATS:
        for r in x.reads:
            assert r in all_sets or r in evidence_ids, f'{x.id} reads unset flag {r}'

    by_act = collections.defaultdict(list)
    for x in BEATS:
        by_act[x.act].append({
            'id': x.id,
            'title': x.title,
            'chapters': list(x.ch),
            'coverage': x.cov,
            'template': x.template,
            'area': x.area,
            'script': f'{x.act}/{x.ch[0]:03d}-{x.id.split(".", 1)[1].replace(".", "-")}.json',
            'requires': list(x.requires),
            'sets': list(x.sets),
            'reads': list(x.reads),
            'evidence': list(x.evidence),
            'cast': list(x.cast),
            'mustLand': x.must,
            'recollection': x.recollection,
            'foresight': x.foresight,
            'art': x.art,
            'sfx': None,
            'music': None,
            'day': x.day,
            'weather': x.weather,
            'legacyStep': legacy_step(x.ch[1]),
            'designNote': x.note,
        })

    root = pathlib.Path('content/qingmao/acts')
    for act, beats in by_act.items():
        p = root / act / 'beats.json'
        p.write_text(json.dumps({
            'act': act,
            'note': 'Beats are addressed by stable ID. legacyStep maps a pre-v5 save\'s step counter onto this graph; inserting a beat never renumbers another.',
            'beats': beats,
        }, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
        print(f'{p}: {len(beats)} beats, chapters {beats[0]["chapters"][0]}-{beats[-1]["chapters"][1]}')
    print(f'total {len(BEATS)} beats, 200/200 chapters covered')
    cov = collections.Counter(x.cov for x in BEATS)
    print('beat coverage levels:', dict(cov))
    chcov = collections.Counter(next(x.cov for x in BEATS if x.id == covered[c]) for c in range(1, 201))
    print('chapter coverage levels:', dict(chcov))
    print('must-land beats:', sorted({x.must for x in BEATS if x.must}))

main()
