# -*- coding: utf-8 -*-
"""Chapters 101-200 of the private ledger. Original writing in Fang Yuan's voice."""
LEDGER_101_200 = {
101: "The application came back approved in principle, which is the clan's way of saying the argument has been moved to a room I am allowed into. Pulled the asset records myself rather than asking for a summary.",
102: "The records are clear and my uncle's position is not. He has been managing property he does not own and reporting the management as ownership for six years.",
103: "Filed the discrepancy. Not as an accusation — as a clerical question. A clerical question is answered by a clerk, and a clerk's answer becomes a document.",
104: "Man Shi carried the record boxes for me because I asked him to and nobody else ever has. He is a head taller than the room and entirely unaware of it. Useful, and not in the way people assume.",
105: "Went looking for people who remember the original arrangement. Three of them do. Two want money and one wants my uncle embarrassed, which is cheaper.",
106: "Paid the two. Recorded the amount, because the point of this ledger is that I never pretend a victory was free.",
107: "My aunt came to the tavern to explain to the room that I was ungrateful. She is effective at this. I let her finish and then asked her, quietly, which year the transfer was recorded in.",
108: "She did not know. Neither does he. A household that cannot date its own paperwork loses to a household that can.",
109: "The council heard it. My uncle spoke first and spoke too long, which is what a man does when his case is a feeling.",
110: "Elder Bo asked for the dates. I gave the dates. There is a particular silence a council makes when the tedious party turns out to be the correct one.",
111: "Adjourned for consideration. Consideration means the elders are counting who is owed what by whom, and I am not owed anything, which in this instance works in my favour.",
112: "Used the adjournment to settle the two witnesses properly and to leave my uncle entirely alone. A man with nothing to react to looks like a man with nothing.",
113: "Found in my favour. The property, the tavern, the leaf terraces and the accounts, transferred on a recorded date that nobody can argue with.",
114: "My uncle asked whether family meant anything to me. I told him it meant a recorded transfer date, which is the only form of it that has ever protected anybody in this clan.",
115: "Took possession. Fang Zheng was in the room and said he hoped this would let us be brothers again. He believed it. I have stopped finding that useful and started finding it inconvenient.",
116: "Word from the Bai clan reached the village before the Bai did. A clan that keeps its own accounts and settles them late. Someone there has a grievance against their own house, and a grievance is a handle.",
117: "Nine Leaf Vitality Grass. It yields leaves on a cycle and a leaf restores vitality, which makes it the only healing I own and the only income I can predict.",
118: "Jiang Ya buys the leaves at five stones and does not ask where the terraces came from. Prices first, pleasantries after. My preferred kind of merchant.",
119: "Attempted Moonglow. The refinement did not take. Lost the materials and the better part of a week.",
120: "Went back over the recipe. The error was not in the recipe. Some refinements fail because refinement is uncertain, and instructors who tell students otherwise are managing morale, not teaching.",
121: "Re-bought the materials out of leaf income. The failure cost eleven stones and nine days, and it did not cost me Moonlight Gu, which is the only line in that sentence that mattered.",
122: "Second attempt. Slower, colder, and with the ingredients measured twice, because the first failure was not a recipe problem and I had nothing else to change.",
123: "Moonglow Gu. Rank two ranged, and it replaces the crescent as the thing I actually fight with.",
124: "Retired the Moonblade to practice. Kept Moonlight Gu fed anyway. A Gu you stop feeding is a Gu you no longer own, and I do not give things away on the assumption that I will never need them.",
125: "The tavern has a wage bill, a supplier, a stock loss and a landlord, and as of this month the landlord is me. The arithmetic is the same arithmetic as the aperture: income, upkeep, margin.",
126: "Traded for a Black Boar Gu and kept the strength after the trade went through. Strength that survives the sale of its source is the closest thing to free money I have found on this mountain.",
127: "Man Shi broke a table and then repaired it badly. Put him on the door instead. A troublemaker pointed outward is a fixture.",
128: "Four Flavours needs a second Liquor worm. Bought one, which means I have spent real money to destroy a Gu I paid for, in order to make a Gu that eats more than both of them did.",
129: "Spent three days confirming the recipe against two sources before touching the materials. The last failure taught me what nine days cost.",
130: "Refined it, and it took. Two sources, three days of checking and a steadier hand than I had in month nine.",
131: "Four Flavours Liquor worm. It raises Rank two essence by a small stage, and it drinks six stones' worth of wine every four days. My income now has a job and the job is feeding a worm.",
132: "Bought Stealth Scales from the medicine hall's back shelf. Ordinary wolves lose track of what wears it.",
133: "And Earth Communication Ear Grass, which marks what is moving through the ground. Together they cost nineteen stones and they are the reason I expect to survive the season.",
134: "Tested both on the lower slopes. Concealment holds while I am walking and fails when I am fighting. Noted, because the failure mode is the whole design of this winter.",
135: "The tide is coming. Nobody argues with the season; they argue about the roster, which is how a village spends the last quiet week it will get.",
136: "Qing Shu has been given the forward position. He is old, he is scarred, and he asked for the equipment rather than the honour, which is how I know he understands the assignment.",
137: "The village is fortifying. I bought water shield stock instead of helping, and the difference between those two activities is the difference between me and Qing Shu.",
138: "Water Shield Gu, recorded and stored. White Jade stays equipped. Redundancy is cheap when it is bought before it is needed.",
139: "Into the forest. Lightning wolves, and not one kind of them — the small fast ones drive, the heavy ones arrive afterward. The pack is a structure, not a crowd.",
140: "Concealed and moved. Two hours of crossing that would have been twenty minutes of fighting, and I finished with essence in hand.",
141: "Fought once, because a ravine gave me no alternative. Spent a third of the sea on four wolves. That exchange rate is the argument for never fighting.",
142: "Listened through the soil at the ridge and counted what was behind the first wave. There is no position on this mountain that holds against that number. Qing Shu's included.",
143: "Found his position from above. He had it arranged properly — lines, reliefs, a fallback. It was competent and it was not going to be enough, and both of those things were visible from where I stood.",
144: "Watched. I will not dress that word up. I was concealed, I had leaves, and I had the essence to intervene, and I chose the ridge.",
145: "It fell at dusk. He was organising a relief that no longer existed when it stopped. I came down the other side of the ridge and arrived in the village with everybody else. Nothing about that day requires explanation, and nobody has asked for one.",
146: "The tally: the forward position gone, the second line holding, a third of the forest burnt. The village will be talking about Qing Shu for twenty years, and it will be talking about him accurately.",
147: "Leaf prices doubled. Wounded people need vitality and there is only one supply on this mountain. I did not raise my price. A man who gouges during a disaster is a man people remember clearly.",
148: "The tavern was full every night for a week. Grief drinks. Took the income and said the right things to the right people at the right volume.",
149: "Closed the season's accounts. Up four hundred and sixty stones, net of upkeep. I have never been this solvent and I have never been this close to needing to leave.",
150: "Met a Yao girl in the forest past the second ridge. Soaked through, frightened, and visibly relieved to see a face from the village. She said my name like it was good news.",
151: "What I needed was in front of me and it had a name and it was glad to see me. I am not going to write the rest of it here. The ledger records cost, and the cost was a person who trusted the wrong face.",
152: "Rank three. White silver. Genuine, verifiable, and the clan will examine the result long before it examines the route. The site is three things now: a location, an absence, and a last-seen.",
153: "The council acknowledged the rank. Chi Lian spoke in favour as though we had an arrangement of long standing, which we do not, and which it is now in both our interests to let stand.",
154: "An elder at fifteen. The smiles in that hall were real gestures of power and none of them were trust. Yao Ji was outside the hall asking people about her sister.",
155: "An elder can requisition what a student could only look at. Sky Canopy for defence, Thunderwings for distance. Sky Canopy replaces White Jade; Thunderwings is the first thing I have owned that makes leaving a plan instead of a wish.",
156: "Reviewed the clan's Rank three recipes. Most of them bind the holder to clan supply lines through the diet. Convenient for the clan.",
157: "Chose Blood Moon and refined it without error. A red crescent with a second hit that lands late. Its diet is blood, which is available anywhere there are animals, which is everywhere I am going.",
158: "Chi Zhong has inherited the medical administration and is pressing an order his predecessor could not enforce. He is young for the post and he quotes regulations at people who outrank him.",
159: "Complied with the order, publicly, at a small cost. A new elder who fights the first requisition is a new elder with a file.",
160: "Yao Ji has been asking the same question, in the same words, for five weeks. The village has started avoiding her, which helps me and costs her.",
161: "Walked the route back to see what I had left behind. A path that is used more than it should be, and two people who can date the afternoon.",
162: "Cleaned what could be cleaned. Two stones to a carter with a poor memory and a better one afterward. The third item cannot be cleaned, only contradicted, and contradictions need a second story to lean on.",
163: "Built the second story out of three true facts and one arrangement of them. That is the strongest kind, and it is the kind that survives an investigator.",
164: "Added the Chainsaw Golden Centipede. Close range, expensive per swing. I do not intend to use it and I intend very much to have it.",
165: "Practised with it away from the village. Everything I equip now is chosen for a road rather than for a clan.",
166: "Priced the full inventory's upkeep at Rank three. It is roughly four times what it was in winter. Being an elder is a job with a subscription.",
167: "Requisitioned travelling supplies through the medicine hall on a legitimate order. Chi Zhong signed it because the paperwork was correct.",
168: "Tusita Flower. Storage, and the reason a departure can be packed in advance without anyone seeing luggage.",
169: "Packed. Thirty chapters early, by the calendar of my own intentions. Nobody in this village would believe how long I have been leaving.",
170: "Tie Ruo Nan arrived. Travelling clothes, a notebook, and the unhurried attention of somebody who expects to be lied to and is not offended by it.",
171: "She did not open with Yao Le. She opened with Jia Jin Sheng, which means she read the old inquiry before she came, which means she is better than Jia Fu was.",
172: "Gave her the fossil account and the dates. She wrote both down and asked me to repeat one detail. I repeated it identically, which is what a true account does and also what a rehearsed one does.",
173: "She is going to walk the places. I have known that since chapter fifty-nine and I have spent two years making the places boring.",
174: "She went up the bamboo path. There is a trail there that does not lead anywhere interesting any more, and it took me four separate afternoons across two years to make that true.",
175: "She asked the carter. He told her about a cart, a junction and nothing else, because that is now all he has.",
176: "She asked why a Rank one student's essence readings from two winters ago do not match a Rank two's. Nobody else in two years has asked that question. I had an answer ready and I did not enjoy using it.",
177: "Tie Xue Leng is with her now. He has asked me nothing. He watches, and when he speaks it will be a conclusion rather than a question.",
178: "She has a theory. It is coherent, it fits most of the evidence, and it is wrong, and it is wrong in a direction she chose herself.",
179: "It is wrong because of the two pieces I removed and the one I arranged. If I had left the first of those in place it would be right, and I would be finished.",
180: "Presented her theory to the council. They accepted it. Jia Fu did not, and Jia Fu has no standing and no evidence, which is where he has been since chapter fifty-nine.",
181: "Closed. I have recorded the exact margin by which this did not go the other way, because I intend to remember it as a near miss and not as a talent.",
182: "There is something under the clan. Not a vault — a purpose. I went down because the alternative was to wait for it to come up.",
183: "The chamber is larger than any room on this mountain and it was not built for the living. Whoever designed the Gu Yue clan was not designing a clan.",
184: "Took the Heavenly Essence Treasure Lotus. Nothing prevented me, which is the part that concerns me.",
185: "The founder is down here and he has been down here the whole time. The clan has spent three hundred years celebrating a story about a man who is currently beneath its floor.",
186: "Lord Sky Crane came over the mountain from Central Continent with a grudge that predates everyone now standing on it. The clan is furniture to him.",
187: "Used the Stone Aperture Gu. Rank three peak, inside a quarter of an hour, in a chamber that was built to make exactly that offer.",
188: "It is expended, and with it the chance of anything beyond this rank. I traded my ceiling for my survival and I would do it again, and I am writing it down as a loss because that is what it is.",
189: "The blood lake is not a lake. Stood at the edge of it and understood, finally, what the founder's history was an advertisement for.",
190: "The two of them began, and the scale of it put every fight I have had on this mountain into its proper category. Duels, examinations, wolves. Training.",
191: "Kept to the edges. There is no version of that fight in which I am a participant and a version in which I am a survivor, and only one of those is available.",
192: "Bai Ning Bing came down into it, which I did not arrange and did not prevent. There is a difference between those two and nobody down there was keeping score.",
193: "Fang Zheng was carried off toward Central Continent, unconscious and alive. Alive is the part that is going to cost somebody later. I am recording it so that I do not forget where he went.",
194: "The curtain went up over the mountain. I will record the decision and not the arithmetic under it, because the arithmetic does not improve on a second reading.",
195: "It went wrong. Badly, and in a way I had not priced, which is the first time in two lives I can write that sentence honestly.",
196: "Used the Cicada. The second time in two lives, and the last one I have, spent on a mountain I was already finished with.",
197: "Spring, then autumn, and a short distance backward. Knowing exactly what is about to happen is not the same as being able to stop it, and the second time through I did not try to stop all of it.",
198: "Out across the glacier, with the mountain behind me doing what mountains do when something that old finishes with them. I did not look back at it, and not for any reason worth recording.",
199: "Gave Bai the Yin Gu. The arm is back and something else is different, and we both watched it happen without discussing it. I kept Yang. That is not an oversight and Bai knows it is not an oversight.",
200: "A raft on the Yellow Dragon River. Rank one, no healing Gu, one companion I control through a Gu I did not give away, and the Southern Border ahead of us. Qing Mao is finished. I have been here before — not this river, but this position — and last time it took five hundred years. I know several things now that I did not know then.",
}
