# -*- coding: utf-8 -*-
"""Chapters 1-100 of the private ledger. Original writing in Fang Yuan's voice."""
LEDGER_1_100 = {
1: "Eight of them, and none willing to be the first through the door. I spent what I had left making the arithmetic clear to them. When the accounting no longer favoured me I reached for the Cicada, which is the one thing in five hundred years I never spent.",
2: "Spring, then autumn. The sum of a life drawn back to its opening balance. I did not feel it as mercy; I felt it as a ledger closed and reopened on the first page.",
3: "Rain on the bamboo. Fifteen years old, a thin blanket, an aperture that does not exist yet, and twelve primeval stones to my name. The room is exactly as I remember it, which means everything in it is already accounted for.",
4: "The Hope Gu gathered and the aperture opened. Forty-four percent. The elder read it out the way a clerk reads a figure he has read ten thousand times, and the crowd agreed with him.",
5: "My brother's grade was read second, and the hall behaved as though a verdict had been handed down on both of us. A grade, one hundred percent. He will be funded. I will be tolerated. Both of those are useful to know precisely.",
6: "Walked the mountain afterward to put distances back in my legs. Spear bamboo, straight and sharpened at the tip, exactly where it stood five centuries ago. The landscape is the only thing here that has not changed its mind about me.",
7: "Took Moonlight Gu from the Gu room. A pale crescent, cold as jade, and the clan's signature because the clan owns the method of breeding it. Convenient for them. The first thing I learned about it is what it eats.",
8: "Two primeval stones for a jar of Green Bamboo Wine. Out of twelve that is a sixth of everything I have, spent on a smell. Anyone watching would call it a boy wasting money, and I intend for them to.",
9: "My uncle keeps the house, the furniture and the accounts that were my father's. He called me nephew four times in one conversation, which is three more than necessary.",
10: "My aunt serves tea and an itemised grievance with it. She has decided we are a debt the household is carrying. I let her believe the debt will never be called in.",
11: "Fang Zheng asked whether I was angry about the grades. He meant it kindly. I told him the grades were accurate, which is true and not an answer, and watched him accept it.",
12: "Set the wine out on the mountain after dark. Nothing on the first night, nothing on the second. The memory says a wine-loving Gu lives here; it does not say which crevice, and five hundred years is a long time for a crevice to stay the same shape.",
13: "Fourth night. A bead of white light came out of the bamboo, drank, and went northeast at a speed I had to spend essence to match. I have seen worse returns on two stones.",
14: "The crevice opens into a cave with remains in it. A monk, by the vessels. Dead long enough that the clan has had time to build a different story over the top of him.",
15: "An image wall, still running on an exhausted Photo-audio Gu. What it shows does not match what the clan celebrates every spring. I watched it three times to be certain I could repeat it without error.",
16: "Noted the entrance traces I left: crushed bamboo at the mouth, a scuffed ledge, one footprint in wet clay. Ordinary, individually. Together they are a direction for anyone who thinks to look.",
17: "The worm will not be taken by hand. It is faster than I am and it has no reason to trust a jar twice. Spent two more nights on the problem than I would have liked.",
18: "Considered and discarded the clan's methods, all of which require telling the clan. An advantage announced is an advantage surrendered.",
19: "Used the Cicada's weight on it, and the resistance went out of the worm like water out of a cracked jar. I now own something no fifteen-year-old on this mountain can explain, and a cave nobody knows I can find. The wall will go dark eventually. I will still know where it is.",
20: "The worm refines essence by a small stage while it is fed, and it is fed on wine, which costs stones, which I do not have. The cultivation is free. The appetite is not.",
21: "Confirmed what I remembered: it will not raise Rank two essence. Whatever advantage this gives me has a ceiling, and the ceiling arrives before the danger does. Plan accordingly.",
22: "Moonblade practice in the courtyard. Three straw targets, and every clean strike empties a measurable portion of the sea. Knowing the motion is not the same as owning the motion.",
23: "Second day of drills. The elder corrects my stance, which is the stance of a swordsman who has been dead for five centuries. I let him correct it. A boy who already knows everything is a boy somebody investigates.",
24: "Third day. I can place three strikes without pausing to breathe. The useful number is not the damage; it is how many strikes stand between me and an empty aperture.",
25: "Stopped Mo Yan at the academy gate after class and explained what his continued comfort was worth. He paid. Not because he was frightened of me — because paying was cheaper than the conversation.",
26: "Second collection. Same gate, same hour. Predictability is the whole product: he budgets for it, and a budgeted loss is one nobody complains about loudly.",
27: "Third collection. Two of his friends stayed to watch and then left without him, which told him more about his position than I did.",
28: "Raised the rate. Still inside what his allowance absorbs. The ceiling on extortion is not courage, it is household accounting.",
29: "Counted the week: enough for the worm's wine and a margin. Also counted witnesses. Four students can place me at that gate, and one of them takes notes for a living.",
30: "Someone has started counting on the other side. Elder Mo Chen asked me two questions in the corridor, both of them answerable, neither of them idle.",
31: "He does not have evidence. He has a pattern and the patience to wait for it to resolve. That is a worse opponent than a witness.",
32: "The Mo family sent word through the academy rather than through the clan, which means they want this settled quietly. Quiet is expensive for them and cheap for me.",
33: "Mo Bei came to the academy himself and stood in a classroom doorway as if the doorway owed him the space. I stood up when he entered. It cost nothing and it made his entrance smaller.",
34: "They sent a servant with a cudgel to the bamboo path at dusk. He had no expectation of resistance, which is the only part of their planning I will describe as competent.",
35: "Dealt with it. The decision took longer than the act. I will not write the act down; the ledger is for costs, and the cost here was time and one set of livery I had to account for.",
36: "Evidence on the path: a body that cannot stay there, livery with a household mark on it, and one cart driver who passed the junction four minutes too early. Three problems, three different prices.",
37: "The village has decided a servant ran off with something. I did not build that story. I simply did not interfere with it, which is usually cheaper than building one.",
38: "Mo Bei came to terms in a classroom with the elder present. I said very little. The advantage in that room was not strength and it was not leverage — it was being the only person in it who was not afraid of how the conversation looked.",
39: "The caravan is in. Unusual Gu, overpriced, and a gambling-stone stall that prices uncertainty better than most clans price certainty.",
40: "Lost four stones on two shells. The merchant is honest in the way a scale is honest: he does not cheat, he simply knows the odds he is selling.",
41: "Bought a Mudskin Toad Gu, mostly so that the rest of what I bought would look like an afterthought. Minor protection. Its real function is to be the thing I talk about.",
42: "Watched the stall long enough to learn which shells the merchant handles gently. A purple-gold shell is sealed, and a sealed shell can have contained anything.",
43: "Three stones for the fossil. As of today the Liquor worm came out of a gambling stone at a travelling market in front of witnesses. The cover story is worth more than the worm's refinement and it cost less than the wine.",
44: "Someone followed me onto the mountain after dark. Jia Jin Sheng, armed, and confident in a way that only makes sense if he has already decided how the evening ends.",
45: "Let him follow. A pursuer who believes he is hunting chooses the ground, and a pursuer who chooses the ground can be told which ground to choose.",
46: "Took the high path toward the ravine and he came, the way a man comes when he believes he is choosing. The useful thing about arrogance is that it is navigable.",
47: "It is done. I will record what it cost instead of what it looked like: essence, most of one evening, and a margin of luck I do not intend to need again.",
48: "Cleanup. His trail up the mountain, one villager who saw him leave, residue from a Gu I did not use, and a disappearance that will be reported by morning. Cleaned what could be cleaned and priced the rest.",
49: "He is a missing clan youth now, which is a category the clan has procedures for. Procedures are slower than suspicion and they leave a record. I would rather be in a record than in a rumour.",
50: "Pressed against the aperture wall until the membrane moved. Rank one, middle stage. A small step, taken on schedule, paid for in wine and stones and one evening on the mountain. The road is long and I have walked it before.",
51: "Jia Fu opened an inquiry. He is grieving and he is formal, and he has arranged the second to hold the first. I came with my fossil and my dates in order.",
52: "He asked where the Liquor worm came from. I said the caravan, the purple-gold shell, the market, the witnesses. All of it is true and none of it is the answer.",
53: "They brought out Bamboo Gentleman. It stays green while the speaker is telling the truth, and it stayed green. I will not pretend that was my doing.",
54: "Second session. He asked the same question with different words, which is what a man does when the evidence has run out and the certainty has not.",
55: "He asked about the night itself. I accounted for my evening in the kind of detail nobody invents and nobody enjoys listening to.",
56: "What he has: a missing cousin, a youth who was on the mountain, and an instinct. What he needs: one piece of anything. I spent the week making sure the cheapest piece was already gone.",
57: "Third session, shorter. The elders are tired of it. An inquiry that cannot produce a finding becomes an expense, and expenses end themselves.",
58: "Closed without a finding. I did not win this; I was not convicted, which is a different and more durable outcome.",
59: "Jia Fu said, in front of the council, that he intends to send for an investigator. He named Tie Xue Leng. I wrote the name down and left the page where I would see it again.",
60: "Went back to the cave and broke the wall. The images were finished with; what was behind them was not history, it was a test, and a test implies someone expected a successor.",
61: "Eastern lamps, a passage, and a chamber with a golden Earth Treasury Flower in it. The inheritance hands you what the next obstacle demands. That is either generosity or design, and I have met very little generosity.",
62: "Took Little Light Gu at the Gu room while I was eligible to. It supports the crescent. A star beside the moon; the clan's poetry, my damage figures.",
63: "Second Light. The Moonblade is measurably heavier now, and the cost per strike has not moved. That ratio is the only kind of progress I trust.",
64: "White Boar Gu out of the flower. It increases bodily strength as it is nourished, and the strength stays after the feeding. Permanent returns on a recurring cost. Rare.",
65: "The Wang family hunt this mountain and they keep their knowledge on a beast skin. Not a treasure — working notes. Working notes are worth more.",
66: "Found the rest where they sleep between circuits. Cooking fire, two bowls, a portrait. One occupant, and he is proprietary about the mountain.",
67: "Took the map. I will not write more than that. The cost was an afternoon and a decision I had already made before I walked up.",
68: "Compared it against the copies the clan hands out. The circles on this one have been concealed on those. Somebody has been selling the mountain with pieces removed.",
69: "The map separates animal territory from trap lines. A boar trail to the northeast, a hideout I was not meant to find, and two red circles I will not walk into until I know why they are circled.",
70: "Hunted the trail. Three boars over four days, and the Gu took its share of each. My arms are heavier than they were on Monday.",
71: "Boar blood is the cheapest diet in my inventory, and the hunting that produces it also produces meat I can sell. The only Gu I own that pays for itself.",
72: "Fed it again. Strength is accumulating in a body that was a scholar's body a week ago. The clan will notice eventually; bodies are harder to hide than Gu.",
73: "Stopped counting the boars and started counting the days. Training has a rate, and the rate is what limits me, not the appetite.",
74: "Went back to the hideout with the map in hand. The concealed circles line up with where the occupant does not go. A man's avoidances are his biography.",
75: "A portrait on the wall, fresh ash in the fire, boots by the door in a size I have already measured. Wang Da exists and he is still on this mountain.",
76: "Considered finding him. Decided against it. I know the dangerous ground on this mountain better than he does, and knowledge that lets you avoid a fight is worth more than a fight you win.",
77: "Left the hideout the way I found it. If he never learns the map changed hands, the map keeps working for both of us and only one of us knows it.",
78: "The affairs hall posted a winter roster. Jiao San leads it, and he carries the group's equipment himself, which tells me what kind of leader he is and what kind of loss it would be.",
79: "The boar strength stopped increasing. Reached the ceiling, as remembered, and the passage ahead has a round boulder in it that needed exactly that ceiling. Pushed it up the slope. Jade Skin Gu in the flower behind it: three seconds of guard, three quarters of the damage turned.",
80: "Below the passage the cave opens into a stone forest. I could not see the ceiling from the floor. I went back for a light before I went in, which is the whole lesson of this place.",
81: "Jade-eye monkeys. They conceal themselves against the pillars and their bodies come apart into stone when they are finished. Jade Skin held. Went in twice more to learn the pillars rather than the monkeys.",
82: "The year-end examination is posted. My brother will be in it, funded, equipped and genuinely talented. The clan has already decided what the result means.",
83: "Watched him train for three afternoons. He layers his defences and he changes them in the same order every time, because nobody has ever made him improvise.",
84: "Wrote the order down. Shield, then the second shield, then the retreat. A sequence is not a defence; it is a schedule, and a schedule can be met early.",
85: "First exchange of the duel. He opened exactly as written, in the order I had copied down three afternoons earlier, and the crowd read it as a strong start for him.",
86: "Second phase. I spent essence to break the layer rather than the boy, and the layer did not come back. A defence you cannot reapply is a countdown.",
87: "Won. He was sincere about the handshake, which was worse for him than losing. The clan adjusted its opinion of me by one notch and its opinion of him by none.",
88: "Accepted a mission because refusing it would have been the remarkable choice. Permafrost, decayed soil, a week in the cold, and the pay will not cover the wine.",
89: "Missions are how the clan spends its youths' time so that the time cannot be spent on anything else. I have been aware of this arrangement for five hundred years and I am still inside it.",
90: "Gathered the soil. Jiao San apologises when he gives orders. Noted the quantity, the pay, and the four days I will not get back.",
91: "Cultivated at Jiang He's place. He is incurious, which is precisely what I am paying for, and he does not ask why a Rank one needs privacy.",
92: "Rank two. Red steel. Nobody saw it and nobody will be told. Concealed advancement has a price I am now carrying: every time I fight below my rank, someone who is paying attention gets a free observation.",
93: "The crossing went wrong on the second day. A boar king and lightning wolves, and a group that was organised for soil-gathering.",
94: "Jiao San put himself between the wolves and the youngest of them and kept doing it until he couldn't. I am recording that because it happened, not because it changed what I did.",
95: "Went into the carcass. It was warm and it was the only position on that field that the wolves had no interest in. Survival is frequently undignified and the dignity is never the part that kills you.",
96: "Came out with a snowy tusk and most of my essence. Of the group, a minority walked back down. The clan will hold an inquiry into the loss, because a clan is a thing that holds inquiries.",
97: "Applied for the family-asset mission while the hall was still busy with the inquiry. A request filed during a crisis is a request nobody reads twice.",
98: "Elder Bo took the application and said it would be considered. He means it will be considered by people who owe my uncle nothing in particular, which is the most I can ask for today.",
99: "Refinement room. White Boar and Jade Skin, with the tusk added to improve the binding. The recipe is not certain, whatever the instructors say.",
100: "White Jade Gu. Six seconds of guard and nine tenths of the damage turned. It cost the tusk, eight stones and two days. Without the tusk it would have cost more days and more stones, and I would still have it, because some things on this road are only ever a question of price.",
}
